[package]
name = "tetris"
version = "0.1.0"
authors = ["cdreher <dre19002@byui.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
termion = "1.5.5"
rand = "0.8.0"
